class Runner1 {

    public static void main(String[] args) {

        Notebook notebook1 = new Notebook();
        Notebook notebook2 = new Notebook();

        System.out.println("Notebook 1 Reference : " + notebook1);
        System.out.println("Notebook 2 Reference : " + notebook2);

        System.out.println("Printing Notebook 1 details");
        System.out.println(notebook1.brand);
        System.out.println(notebook1.model);
        System.out.println(notebook1.processor);
        System.out.println(notebook1.ramSize);
        System.out.println(notebook1.storageSize);
        System.out.println(notebook1.storageType);
        System.out.println(notebook1.screenSize);
        System.out.println(notebook1.operatingSystem);
        System.out.println(notebook1.price);
        System.out.println(notebook1.color);
        System.out.println(notebook1.weight);
        System.out.println(notebook1.batteryCapacity);
        System.out.println(notebook1.batteryLife);
        System.out.println(notebook1.isTouchScreen);
        System.out.println(notebook1.graphicsCard);
        System.out.println(notebook1.usbPorts);
        System.out.println(notebook1.hdmiPorts);
        System.out.println(notebook1.hasBluetooth);
        System.out.println(notebook1.hasWifi);
        System.out.println(notebook1.keyboardType);
        System.out.println(notebook1.hasBacklitKeyboard);
        System.out.println(notebook1.warrantyYears);
        System.out.println(notebook1.manufacturingCountry);
        System.out.println(notebook1.releaseYear);
        System.out.println(notebook1.cameraQuality);
        System.out.println(notebook1.hasFingerprintSensor);

        System.out.println("Printing Notebook 2 details");
        System.out.println(notebook2.brand);
        System.out.println(notebook2.model);
        System.out.println(notebook2.processor);
        System.out.println(notebook2.ramSize);
        System.out.println(notebook2.storageSize);
        System.out.println(notebook2.storageType);
        System.out.println(notebook2.screenSize);
        System.out.println(notebook2.operatingSystem);
        System.out.println(notebook2.price);
        System.out.println(notebook2.color);
        System.out.println(notebook2.weight);
        System.out.println(notebook2.batteryCapacity);
        System.out.println(notebook2.batteryLife);
        System.out.println(notebook2.isTouchScreen);
        System.out.println(notebook2.graphicsCard);
        System.out.println(notebook2.usbPorts);
        System.out.println(notebook2.hdmiPorts);
        System.out.println(notebook2.hasBluetooth);
        System.out.println(notebook2.hasWifi);
        System.out.println(notebook2.keyboardType);
        System.out.println(notebook2.hasBacklitKeyboard);
        System.out.println(notebook2.warrantyYears);
        System.out.println(notebook2.manufacturingCountry);
        System.out.println(notebook2.releaseYear);
        System.out.println(notebook2.cameraQuality);
        System.out.println(notebook2.hasFingerprintSensor);

        Clock clock1 = new Clock();
        Clock clock2 = new Clock();

        System.out.println("Clock 1 Reference : " + clock1);
        System.out.println("Clock 2 Reference : " + clock2);

        System.out.println("Printing Clock 1 details");
        System.out.println(clock1.brand);
        System.out.println(clock1.model);
        System.out.println(clock1.type);
        System.out.println(clock1.color);
        System.out.println(clock1.shape);
        System.out.println(clock1.material);
        System.out.println(clock1.price);
        System.out.println(clock1.weight);
        System.out.println(clock1.year);
        System.out.println(clock1.isDigital);
        System.out.println(clock1.hasAlarm);
        System.out.println(clock1.isSmart);
        System.out.println(clock1.isWaterproof);
        System.out.println(clock1.batteryLife);
        System.out.println(clock1.size);
        System.out.println(clock1.displayType);
        System.out.println(clock1.country);
        System.out.println(clock1.design);
        System.out.println(clock1.code);
        System.out.println(clock1.stock);
        System.out.println(clock1.hasLight);
        System.out.println(clock1.isSilent);
        System.out.println(clock1.isPortable);
        System.out.println(clock1.alarmCount);
        System.out.println(clock1.radius);
        System.out.println(clock1.owner);

        System.out.println("Printing Clock 2 details");
        System.out.println(clock2.brand);
        System.out.println(clock2.model);
        System.out.println(clock2.type);
        System.out.println(clock2.color);
        System.out.println(clock2.shape);
        System.out.println(clock2.material);
        System.out.println(clock2.price);
        System.out.println(clock2.weight);
        System.out.println(clock2.year);
        System.out.println(clock2.isDigital);
        System.out.println(clock2.hasAlarm);
        System.out.println(clock2.isSmart);
        System.out.println(clock2.isWaterproof);
        System.out.println(clock2.batteryLife);
        System.out.println(clock2.size);
        System.out.println(clock2.displayType);
        System.out.println(clock2.country);
        System.out.println(clock2.design);
        System.out.println(clock2.code);
        System.out.println(clock2.stock);
        System.out.println(clock2.hasLight);
        System.out.println(clock2.isSilent);
        System.out.println(clock2.isPortable);
        System.out.println(clock2.alarmCount);
        System.out.println(clock2.radius);
        System.out.println(clock2.owner);

        Bangle bangle1 = new Bangle();
        Bangle bangle2 = new Bangle();

        System.out.println("Bangle 1 Reference : " + bangle1);
        System.out.println("Bangle 2 Reference : " + bangle2);

        System.out.println("Printing Bangle 1 details");
        System.out.println(bangle1.material);
        System.out.println(bangle1.color);
        System.out.println(bangle1.design);
        System.out.println(bangle1.brand);
        System.out.println(bangle1.type);
        System.out.println(bangle1.country);
        System.out.println(bangle1.size);
        System.out.println(bangle1.price);
        System.out.println(bangle1.weight);
        System.out.println(bangle1.stock);
        System.out.println(bangle1.code);
        System.out.println(bangle1.year);
        System.out.println(bangle1.isGold);
        System.out.println(bangle1.isSilver);
        System.out.println(bangle1.isAntique);
        System.out.println(bangle1.isHandmade);
        System.out.println(bangle1.isAvailable);
        System.out.println(bangle1.isFlexible);
        System.out.println(bangle1.isPolished);
        System.out.println(bangle1.thickness);
        System.out.println(bangle1.diameter);
        System.out.println(bangle1.pattern);
        System.out.println(bangle1.usage);
        System.out.println(bangle1.quality);
        System.out.println(bangle1.category);
        System.out.println(bangle1.supplier);

        System.out.println("Printing Bangle 2 details");
        System.out.println(bangle2.material);
        System.out.println(bangle2.color);
        System.out.println(bangle2.design);
        System.out.println(bangle2.brand);
        System.out.println(bangle2.type);
        System.out.println(bangle2.country);
        System.out.println(bangle2.size);
        System.out.println(bangle2.price);
        System.out.println(bangle2.weight);
        System.out.println(bangle2.stock);
        System.out.println(bangle2.code);
        System.out.println(bangle2.year);
        System.out.println(bangle2.isGold);
        System.out.println(bangle2.isSilver);
        System.out.println(bangle2.isAntique);
        System.out.println(bangle2.isHandmade);
        System.out.println(bangle2.isAvailable);
        System.out.println(bangle2.isFlexible);
        System.out.println(bangle2.isPolished);
        System.out.println(bangle2.thickness);
        System.out.println(bangle2.diameter);
        System.out.println(bangle2.pattern);
        System.out.println(bangle2.usage);
        System.out.println(bangle2.quality);
        System.out.println(bangle2.category);
        System.out.println(bangle2.supplier);

        Engine engine1 = new Engine();
        Engine engine2 = new Engine();

        System.out.println("Engine 1 Reference : " + engine1);
        System.out.println("Engine 2 Reference : " + engine2);

        System.out.println("Printing Engine 1 details");
        System.out.println(engine1.type);
        System.out.println(engine1.brand);
        System.out.println(engine1.model);
        System.out.println(engine1.fuelType);
        System.out.println(engine1.country);
        System.out.println(engine1.power);
        System.out.println(engine1.weight);
        System.out.println(engine1.year);
        System.out.println(engine1.code);
        System.out.println(engine1.stock);
        System.out.println(engine1.isAutomatic);
        System.out.println(engine1.isRunning);
        System.out.println(engine1.isAvailable);
        System.out.println(engine1.isElectric);
        System.out.println(engine1.cylinders);
        System.out.println(engine1.torque);
        System.out.println(engine1.rpm);
        System.out.println(engine1.capacity);
        System.out.println(engine1.coolingType);
        System.out.println(engine1.usage);
        System.out.println(engine1.quality);
        System.out.println(engine1.category);
        System.out.println(engine1.supplier);
        System.out.println(engine1.color);
        System.out.println(engine1.warranty);
        System.out.println(engine1.isTurbo);

        System.out.println("Printing Engine 2 details");
        System.out.println(engine2.type);
        System.out.println(engine2.brand);
        System.out.println(engine2.model);
        System.out.println(engine2.fuelType);
        System.out.println(engine2.country);
        System.out.println(engine2.power);
        System.out.println(engine2.weight);
        System.out.println(engine2.year);
        System.out.println(engine2.code);
        System.out.println(engine2.stock);
        System.out.println(engine2.isAutomatic);
        System.out.println(engine2.isRunning);
        System.out.println(engine2.isAvailable);
        System.out.println(engine2.isElectric);
        System.out.println(engine2.cylinders);
        System.out.println(engine2.torque);
        System.out.println(engine2.rpm);
        System.out.println(engine2.capacity);
        System.out.println(engine2.coolingType);
        System.out.println(engine2.usage);
        System.out.println(engine2.quality);
        System.out.println(engine2.category);
        System.out.println(engine2.supplier);
        System.out.println(engine2.color);
        System.out.println(engine2.warranty);
        System.out.println(engine2.isTurbo);

        Monitor monitor1 = new Monitor();
        Monitor monitor2 = new Monitor();

        System.out.println("Monitor 1 Reference : " + monitor1);
        System.out.println("Monitor 2 Reference : " + monitor2);

        System.out.println("Printing Monitor 1 details");
        System.out.println(monitor1.brand);
        System.out.println(monitor1.model);
        System.out.println(monitor1.type);
        System.out.println(monitor1.screenSize);
        System.out.println(monitor1.resolution);
        System.out.println(monitor1.refreshRate);
        System.out.println(monitor1.price);
        System.out.println(monitor1.color);
        System.out.println(monitor1.weight);
        System.out.println(monitor1.isCurved);
        System.out.println(monitor1.hasHDMI);
        System.out.println(monitor1.hasVGA);
        System.out.println(monitor1.hasUSB);
        System.out.println(monitor1.usbPorts);
        System.out.println(monitor1.hdmiPorts);
        System.out.println(monitor1.panelType);
        System.out.println(monitor1.country);
        System.out.println(monitor1.year);
        System.out.println(monitor1.usage);
        System.out.println(monitor1.category);
        System.out.println(monitor1.supplier);
        System.out.println(monitor1.isTouch);
        System.out.println(monitor1.isPortable);
        System.out.println(monitor1.warranty);
        System.out.println(monitor1.design);
        System.out.println(monitor1.isAvailable);

        System.out.println("Printing Monitor 2 details");
        System.out.println(monitor2.brand);
        System.out.println(monitor2.model);
        System.out.println(monitor2.type);
        System.out.println(monitor2.screenSize);
        System.out.println(monitor2.resolution);
        System.out.println(monitor2.refreshRate);
        System.out.println(monitor2.price);
        System.out.println(monitor2.color);
        System.out.println(monitor2.weight);
        System.out.println(monitor2.isCurved);
        System.out.println(monitor2.hasHDMI);
        System.out.println(monitor2.hasVGA);
        System.out.println(monitor2.hasUSB);
        System.out.println(monitor2.usbPorts);
        System.out.println(monitor2.hdmiPorts);
        System.out.println(monitor2.panelType);
        System.out.println(monitor2.country);
        System.out.println(monitor2.year);
        System.out.println(monitor2.usage);
        System.out.println(monitor2.category);
        System.out.println(monitor2.supplier);
        System.out.println(monitor2.isTouch);
        System.out.println(monitor2.isPortable);
        System.out.println(monitor2.warranty);
        System.out.println(monitor2.design);
        System.out.println(monitor2.isAvailable);

        Generator generator1 = new Generator();
        Generator generator2 = new Generator();

        System.out.println("Generator 1 Reference : " + generator1);
        System.out.println("Generator 2 Reference : " + generator2);

        System.out.println("Printing Generator 1 details");
        System.out.println(generator1.brand);
        System.out.println(generator1.model);
        System.out.println(generator1.type);
        System.out.println(generator1.fuelType);
        System.out.println(generator1.power);
        System.out.println(generator1.price);
        System.out.println(generator1.weight);
        System.out.println(generator1.year);
        System.out.println(generator1.code);
        System.out.println(generator1.stock);
        System.out.println(generator1.isElectric);
        System.out.println(generator1.isPortable);
        System.out.println(generator1.isAvailable);
        System.out.println(generator1.isAutomatic);
        System.out.println(generator1.capacity);
        System.out.println(generator1.runtime);
        System.out.println(generator1.efficiency);
        System.out.println(generator1.coolingType);
        System.out.println(generator1.country);
        System.out.println(generator1.usage);
        System.out.println(generator1.category);
        System.out.println(generator1.supplier);
        System.out.println(generator1.color);
        System.out.println(generator1.warranty);
        System.out.println(generator1.isSilent);
        System.out.println(generator1.hasWheels);

        System.out.println("Printing Generator 2 details");
        System.out.println(generator2.brand);
        System.out.println(generator2.model);
        System.out.println(generator2.type);
        System.out.println(generator2.fuelType);
        System.out.println(generator2.power);
        System.out.println(generator2.price);
        System.out.println(generator2.weight);
        System.out.println(generator2.year);
        System.out.println(generator2.code);
        System.out.println(generator2.stock);
        System.out.println(generator2.isElectric);
        System.out.println(generator2.isPortable);
        System.out.println(generator2.isAvailable);
        System.out.println(generator2.isAutomatic);
        System.out.println(generator2.capacity);
        System.out.println(generator2.runtime);
        System.out.println(generator2.efficiency);
        System.out.println(generator2.coolingType);
        System.out.println(generator2.country);
        System.out.println(generator2.usage);
        System.out.println(generator2.category);
        System.out.println(generator2.supplier);
        System.out.println(generator2.color);
        System.out.println(generator2.warranty);
        System.out.println(generator2.isSilent);
        System.out.println(generator2.hasWheels);

        Arduino arduino1 = new Arduino();
        Arduino arduino2 = new Arduino();

        System.out.println("Arduino 1 Reference : " + arduino1);
        System.out.println("Arduino 2 Reference : " + arduino2);

        System.out.println("Printing Arduino 1 details");
        System.out.println(arduino1.board);
        System.out.println(arduino1.processor);
        System.out.println(arduino1.memory);
        System.out.println(arduino1.clockSpeed);
        System.out.println(arduino1.digitalPins);
        System.out.println(arduino1.analogPins);
        System.out.println(arduino1.hasUSB);
        System.out.println(arduino1.hasWifi);
        System.out.println(arduino1.hasBluetooth);
        System.out.println(arduino1.price);
        System.out.println(arduino1.brand);
        System.out.println(arduino1.model);
        System.out.println(arduino1.year);
        System.out.println(arduino1.country);
        System.out.println(arduino1.usage);
        System.out.println(arduino1.category);
        System.out.println(arduino1.supplier);
        System.out.println(arduino1.color);
        System.out.println(arduino1.code);
        System.out.println(arduino1.stock);
        System.out.println(arduino1.isAvailable);
        System.out.println(arduino1.isProgrammable);
        System.out.println(arduino1.isPortable);
        System.out.println(arduino1.voltage);
        System.out.println(arduino1.current);
        System.out.println(arduino1.warranty);

        System.out.println("Printing Arduino 2 details");
        System.out.println(arduino2.board);
        System.out.println(arduino2.processor);
        System.out.println(arduino2.memory);
        System.out.println(arduino2.clockSpeed);
        System.out.println(arduino2.digitalPins);
        System.out.println(arduino2.analogPins);
        System.out.println(arduino2.hasUSB);
        System.out.println(arduino2.hasWifi);
        System.out.println(arduino2.hasBluetooth);
        System.out.println(arduino2.price);
        System.out.println(arduino2.brand);
        System.out.println(arduino2.model);
        System.out.println(arduino2.year);
        System.out.println(arduino2.country);
        System.out.println(arduino2.usage);
        System.out.println(arduino2.category);
        System.out.println(arduino2.supplier);
        System.out.println(arduino2.color);
        System.out.println(arduino2.code);
        System.out.println(arduino2.stock);
        System.out.println(arduino2.isAvailable);
        System.out.println(arduino2.isProgrammable);
        System.out.println(arduino2.isPortable);
        System.out.println(arduino2.voltage);
        System.out.println(arduino2.current);
        System.out.println(arduino2.warranty);

        Shampoo shampoo1 = new Shampoo();
        Shampoo shampoo2 = new Shampoo();

        System.out.println("Shampoo 1 Reference : " + shampoo1);
        System.out.println("Shampoo 2 Reference : " + shampoo2);

        System.out.println("Printing Shampoo 1 details");
        System.out.println(shampoo1.brand);
        System.out.println(shampoo1.type);
        System.out.println(shampoo1.fragrance);
        System.out.println(shampoo1.volume);
        System.out.println(shampoo1.price);
        System.out.println(shampoo1.color);
        System.out.println(shampoo1.hairType);
        System.out.println(shampoo1.isOrganic);
        System.out.println(shampoo1.isHerbal);
        System.out.println(shampoo1.isAvailable);
        System.out.println(shampoo1.stock);
        System.out.println(shampoo1.code);
        System.out.println(shampoo1.year);
        System.out.println(shampoo1.country);
        System.out.println(shampoo1.usage);
        System.out.println(shampoo1.category);
        System.out.println(shampoo1.supplier);
        System.out.println(shampoo1.packaging);
        System.out.println(shampoo1.isAntiDandruff);
        System.out.println(shampoo1.isConditioning);
        System.out.println(shampoo1.isMedicated);
        System.out.println(shampoo1.phLevel);
        System.out.println(shampoo1.quality);
        System.out.println(shampoo1.design);
        System.out.println(shampoo1.warranty);
        System.out.println(shampoo1.isLiquid);

        System.out.println("Printing Shampoo 2 details");
        System.out.println(shampoo2.brand);
        System.out.println(shampoo2.type);
        System.out.println(shampoo2.fragrance);
        System.out.println(shampoo2.volume);
        System.out.println(shampoo2.price);
        System.out.println(shampoo2.color);
        System.out.println(shampoo2.hairType);
        System.out.println(shampoo2.isOrganic);
        System.out.println(shampoo2.isHerbal);
        System.out.println(shampoo2.isAvailable);
        System.out.println(shampoo2.stock);
        System.out.println(shampoo2.code);
        System.out.println(shampoo2.year);
        System.out.println(shampoo2.country);
        System.out.println(shampoo2.usage);
        System.out.println(shampoo2.category);
        System.out.println(shampoo2.supplier);
        System.out.println(shampoo2.packaging);
        System.out.println(shampoo2.isAntiDandruff);
        System.out.println(shampoo2.isConditioning);
        System.out.println(shampoo2.isMedicated);
        System.out.println(shampoo2.phLevel);
        System.out.println(shampoo2.quality);
        System.out.println(shampoo2.design);
        System.out.println(shampoo2.warranty);
        System.out.println(shampoo2.isLiquid);

        Iron iron1 = new Iron();
        Iron iron2 = new Iron();

        System.out.println("Iron 1 Reference : " + iron1);
        System.out.println("Iron 2 Reference : " + iron2);

        System.out.println("Printing Iron 1 details");
        System.out.println(iron1.brand);
        System.out.println(iron1.model);
        System.out.println(iron1.type);
        System.out.println(iron1.power);
        System.out.println(iron1.price);
        System.out.println(iron1.color);
        System.out.println(iron1.weight);
        System.out.println(iron1.isSteam);
        System.out.println(iron1.isDry);
        System.out.println(iron1.isAvailable);
        System.out.println(iron1.stock);
        System.out.println(iron1.code);
        System.out.println(iron1.year);
        System.out.println(iron1.country);
        System.out.println(iron1.usage);
        System.out.println(iron1.category);
        System.out.println(iron1.supplier);
        System.out.println(iron1.material);
        System.out.println(iron1.isPortable);
        System.out.println(iron1.hasAutoCut);
        System.out.println(iron1.hasLight);
        System.out.println(iron1.voltage);
        System.out.println(iron1.temperature);
        System.out.println(iron1.design);
        System.out.println(iron1.warranty);
        System.out.println(iron1.isElectric);

        System.out.println("Printing Iron 2 details");
        System.out.println(iron2.brand);
        System.out.println(iron2.model);
        System.out.println(iron2.type);
        System.out.println(iron2.power);
        System.out.println(iron2.price);
        System.out.println(iron2.color);
        System.out.println(iron2.weight);
        System.out.println(iron2.isSteam);
        System.out.println(iron2.isDry);
        System.out.println(iron2.isAvailable);
        System.out.println(iron2.stock);
        System.out.println(iron2.code);
        System.out.println(iron2.year);
        System.out.println(iron2.country);
        System.out.println(iron2.usage);
        System.out.println(iron2.category);
        System.out.println(iron2.supplier);
        System.out.println(iron2.material);
        System.out.println(iron2.isPortable);
        System.out.println(iron2.hasAutoCut);
        System.out.println(iron2.hasLight);
        System.out.println(iron2.voltage);
        System.out.println(iron2.temperature);
        System.out.println(iron2.design);
        System.out.println(iron2.warranty);
        System.out.println(iron2.isElectric);

        Stand stand1 = new Stand();
        Stand stand2 = new Stand();

        System.out.println("Stand 1 Reference : " + stand1);
        System.out.println("Stand 2 Reference : " + stand2);

        System.out.println("Printing Stand 1 details");
        System.out.println(stand1.type);
        System.out.println(stand1.material);
        System.out.println(stand1.color);
        System.out.println(stand1.height);
        System.out.println(stand1.width);
        System.out.println(stand1.price);
        System.out.println(stand1.weight);
        System.out.println(stand1.isFoldable);
        System.out.println(stand1.isPortable);
        System.out.println(stand1.isAvailable);
        System.out.println(stand1.stock);
        System.out.println(stand1.code);
        System.out.println(stand1.year);
        System.out.println(stand1.country);
        System.out.println(stand1.usage);
        System.out.println(stand1.category);
        System.out.println(stand1.supplier);
        System.out.println(stand1.design);
        System.out.println(stand1.isAdjustable);
        System.out.println(stand1.isStrong);
        System.out.println(stand1.isLight);
        System.out.println(stand1.capacity);
        System.out.println(stand1.quality);
        System.out.println(stand1.brand);
        System.out.println(stand1.warranty);
        System.out.println(stand1.isStable);

        System.out.println("Printing Stand 2 details");
        System.out.println(stand2.type);
        System.out.println(stand2.material);
        System.out.println(stand2.color);
        System.out.println(stand2.height);
        System.out.println(stand2.width);
        System.out.println(stand2.price);
        System.out.println(stand2.weight);
        System.out.println(stand2.isFoldable);
        System.out.println(stand2.isPortable);
        System.out.println(stand2.isAvailable);
        System.out.println(stand2.stock);
        System.out.println(stand2.code);
        System.out.println(stand2.year);
        System.out.println(stand2.country);
        System.out.println(stand2.usage);
        System.out.println(stand2.category);
        System.out.println(stand2.supplier);
        System.out.println(stand2.design);
        System.out.println(stand2.isAdjustable);
        System.out.println(stand2.isStrong);
        System.out.println(stand2.isLight);
        System.out.println(stand2.capacity);
        System.out.println(stand2.quality);
        System.out.println(stand2.brand);
        System.out.println(stand2.warranty);
        System.out.println(stand2.isStable);

    }
}